# Generated by Django 3.2 on 2021-04-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210424_1640'),
        ('users', '0005_auto_20210424_1158'),
    ]

    operations = [
    ]
