# Generated by Django 3.2 on 2021-04-24 16:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_0004_auto_20210424_1640_0005_auto_20210424_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Seller', 'SELLER'), ('Customer', 'CUSTOMER')], default=[], max_length=15, null=True),
        ),
    ]
